const { logger } = require('../middleware/logger');
const ConversationRepository = require('../data/repositories/ConversationRepository');
const { generateAICompletion } = require('./aiService');
const { sendToConversation } = require('../utils/websocket');
const { getUserId } = require('../utils/userUtils');
const tokenValidator = require('../../../../shared/utils/tokenValidator');

class ConversationService {
  constructor() {
    this.useMock = process.env.USE_MOCK === 'true';
  }

  async sendMessage(input, userId, io, userToken) {
    try {
      const { title = '', prompt = '', message, conversationId = null, settings = {} } = input;
      let conversation;
      let isNewConversation = false;
      // Normalize userId
      const normalizedUserId = getUserId({ id: userId });
      // Real token check (pass userToken)
      const requiredTokens = 10; // You may want to estimate this based on message length/settings
      const tokenCheck = await tokenValidator.checkTokenBalance(userToken, requiredTokens);
      if (!tokenCheck.hasSufficientTokens) {
        throw new Error('Insufficient tokens available');
      }
      if (conversationId) {
        conversation = await ConversationRepository.findById(conversationId);
        if (!conversation) throw new Error('Conversation not found');
        if (conversation.userId !== normalizedUserId) throw new Error('Unauthorized access to conversation');
        if (!conversation.isActive) throw new Error('This conversation is no longer active');
      } else {
        conversation = await ConversationRepository.create({
          userId: normalizedUserId,
          title: title || (message ? message.substring(0, 30) : 'New Conversation'),
          prompt: prompt || '',
          messages: [],
          settings: settings || {},
          status: 'pending',
          isActive: true
        });
        isNewConversation = true;
        if (prompt) {
          const sysMsg = {
            role: 'system',
            content: prompt,
            timestamp: new Date()
          };
          conversation.messages.push(sysMsg);
          if (io) sendToConversation(io, conversation._id, 'message-added', sysMsg);
        }
      }
      const userMsg = {
        role: 'user',
        content: message,
        timestamp: new Date()
      };
      conversation.messages.push(userMsg);
      if (io) sendToConversation(io, conversation._id, 'message-added', userMsg);
      conversation.status = 'pending';
      conversation.lastMessageAt = new Date();
    await conversation.save();
      const history = conversation.messages.map(msg => ({ role: msg.role, content: msg.content }));
      let aiResponse;
      if (this.useMock) {
        aiResponse = {
          message: `This is a mock AI response to: "${message}"\n\nIn a real environment, this would be generated by an AI model based on the conversation history.`,
          tokensConsumed: Math.ceil(message.length / 4)
        };
        await new Promise(resolve => setTimeout(resolve, 1000));
      } else {
        // Use aiService directly
        const aiResult = await generateAICompletion({ messages: history, settings: settings || {} });
        if (!aiResult.success) throw new Error(aiResult.error || 'AI generation failed');
        aiResponse = {
          message: aiResult.data.content,
          tokensConsumed: aiResult.data.tokens?.total || Math.ceil(aiResult.data.content.length / 4)
        };
      }
      const assistantMessage = {
        role: 'assistant',
        content: aiResponse.message,
        timestamp: new Date()
      };
      conversation.messages.push(assistantMessage);
      if (io) sendToConversation(io, conversation._id, 'message-added', assistantMessage);
      conversation.tokensConsumed = (conversation.tokensConsumed || 0) + aiResponse.tokensConsumed;
      conversation.status = 'completed';
      if (isNewConversation && !title) {
        conversation.title = this.generateTitle(message);
      }
    await conversation.save();
      // Real token deduction (pass userToken)
      await tokenValidator.deductTokens(userToken, aiResponse.tokensConsumed);
      logger.info(`Message processed in conversation: ${conversation._id}`);
      return {
        conversation,
        lastMessage: {
          id: conversation.messages.length - 1,
          conversationId: conversation._id.toString(),
          role: assistantMessage.role,
          content: assistantMessage.content,
          timestamp: assistantMessage.timestamp
        }
      };
    } catch (error) {
      logger.error(`Conversation error: ${error.message}`);
      throw error;
    }
  }

  generateTitle(message) {
    const firstSentence = message.split(/[.!?]/)[0];
    const title = firstSentence.length > 30 ? firstSentence.substring(0, 30) + '...' : firstSentence;
    return title;
  }

  async updateTitle(id, title, userId) {
    try {
      const conversation = await ConversationRepository.findById(id);
      if (!conversation) throw new Error('Conversation not found');
      if (conversation.userId !== userId) throw new Error('Unauthorized access to conversation');
      conversation.title = title;
      await conversation.save();
      return conversation;
    } catch (error) {
      logger.error(`Error updating conversation title: ${error.message}`);
      throw error;
    }
  }

  async archive(id, userId) {
    try {
      const conversation = await ConversationRepository.findById(id);
      if (!conversation) throw new Error('Conversation not found');
      if (conversation.userId !== userId) throw new Error('Unauthorized access to conversation');
      conversation.isArchived = true;
      await conversation.save();
      return conversation;
    } catch (error) {
      logger.error(`Error archiving conversation: ${error.message}`);
      throw error;
    }
  }

  async delete(id, userId) {
    try {
      const conversation = await ConversationRepository.findById(id);
      if (!conversation) throw new Error('Conversation not found');
      if (conversation.userId !== userId) throw new Error('Unauthorized access to conversation');
      await ConversationRepository.updateById(id, { $set: { isActive: false, isArchived: true } });
      return true;
    } catch (error) {
      logger.error(`Error deleting conversation: ${error.message}`);
      throw error;
    }
  }

  async getUserConversations(userId, { page = 1, limit = 20 } = {}) {
    const offset = (page - 1) * limit;
    const query = { userId, isActive: true, isArchived: false };
    return await ConversationRepository.find(query, { sort: { lastMessageAt: -1 }, skip: offset, limit });
  }

  async getById(id, userId) {
    const conversation = await ConversationRepository.findById(id);
    if (!conversation) throw new Error('Conversation not found');
    if (conversation.userId !== userId) throw new Error('Unauthorized access to conversation');
    return conversation;
  }
}

const conversationService = new ConversationService();
module.exports = {
  conversationService
}; 